name: Build with CMake

on:
  # pull_request:
  workflow_dispatch:

env:
  CMAKE_VERSION: 3.30.0
  NINJA_VERSION: 1.13.2

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Qt 5.15.2
          - name: "Ubuntu GCC Qt 5.15.2"
            os: ubuntu-latest
            qt-version: "5.15.2"
            qt-arch: gcc_64

          # - name: "Windows MSVC Qt 5.15.2"
          #   os: windows-latest
          #   qt-version: "5.15.2"
          #   qt-arch: win64_msvc2019_64

          # # Qt 6.9.3
          # - name: "Ubuntu GCC Qt 6.9.3"
          #   os: ubuntu-latest
          #   qt-version: "6.9.3"
          #   qt-arch: linux_gcc_64

          # - name: "macOS Clang Qt 6.9.3"
          #   os: macos-latest
          #   qt-version: "6.9.3"
          #   qt-arch: clang_64

          # - name: "Windows MSVC Qt 6.9.3"
          #   os: windows-latest
          #   qt-version: "6.9.3"
          #   qt-arch: win64_msvc2022_64

    steps:
      - uses: actions/checkout@v4

      - uses: lukka/get-cmake@latest
        with:
          cmakeVersion: ${{ env.CMAKE_VERSION }}
          ninjaVersion: ${{ env.NINJA_VERSION }}

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          cache: true
          version: ${{ matrix.qt-version }}
          arch: ${{ matrix.qt-arch }}

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        if: contains(matrix.name, 'MSVC')

      - uses: ashutoshvarma/action-cmake-build@master
        with:
          build-dir: ${{ github.workspace }}/build
          build-type: Release
          configure-options: >-
            -G Ninja
            -DQUNITCONV_QT_TESTS=ON

      - run: ctest --test-dir ${{ github.workspace }}/build --output-on-failure --verbose
